version: '3.8'

services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:16-alpine 
    environment:
      POSTGRES_USER: pancho
      POSTGRES_PASSWORD: pass123 
      POSTGRES_DB: agenda_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - examen_FJSS
    deploy:
      placement:
        constraints:
          - "node.hostname == Worker-2"

  # --- APLICACIÓN ---
  agenda:
    image: adminjavier/ex_u3_agenda:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://pancho:pass123@db:5432/agenda_db"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5050:5050"
    networks:
      - examen_FJSS

networks:
  examen_FJSS:
    external: true

volumes:
  db_data: